export { InventoryCapabilities } from "./src/capabilities.ts"
export {
  InventoryAdjustStockAction,
  InventoryStockCorrectedEvent,
  InventoryTypedActionCatalog,
  InventoryTypedEventCatalog,
  StockCorrectedEventPayload,
} from "./src/catalog.ts"

export {
  AdjustStockInput,
  CompleteStockTransferInput,
  ConfirmStockTransferInput,
  CreateItemInput,
  CreateStockTransferInput,
  CreateWarehouseInput,
  FulfillReservationInput,
  InventoryReferenceNotFound,
  InventoryService,
  InventoryUnitOfMeasureMismatch,
  InventoryWarehouseLegalEntityMismatch,
  Item,
  ItemAlreadyExists,
  makeInventoryService,
  makeInventoryTestLayer,
  ReceiveStockInput,
  ReleaseReservationInput,
  ReserveStockInput,
  StockBalance,
  StockCorrection,
  StockCorrectionIdempotencyConflict,
  StockReservation,
  StockReservationIdempotencyConflict,
  StockReservationInvalidState,
  StockReservationLegalEntityMismatch,
  StockReservationNotFound,
  StockReservationStatus,
  StockTransfer,
  StockTransferDifferentLegalEntity,
  StockTransferDuplicateItem,
  StockTransferInvalidState,
  StockTransferItemNotFound,
  StockTransferLine,
  StockTransferNotFound,
  StockTransferSameWarehouse,
  StockTransferStatus,
  StockTransferWarehouseNotFound,
  StockUnavailable,
  Warehouse,
  WarehouseAlreadyExists,
  WarehouseBranchNotFound,
  WarehouseLegalEntityNotFound,
} from "./src/service.ts"
export type {
  InventoryService as InventoryServiceShape,
  Item as ItemType,
  StockBalance as StockBalanceType,
  StockCorrection as StockCorrectionType,
  StockReservation as StockReservationType,
  StockTransfer as StockTransferType,
  StockTransferLine as StockTransferLineType,
  Warehouse as WarehouseType,
} from "./src/service.ts"
