export {
  CompleteStockTransferInput,
  ConfirmStockTransferInput,
  CreateItemInput,
  CreateStockTransferInput,
  CreateWarehouseInput,
  InventoryReferenceNotFound,
  InventoryService,
  Item,
  ItemAlreadyExists,
  makeInventoryService,
  makeInventoryTestLayer,
  ReceiveStockInput,
  ReserveStockInput,
  StockBalance,
  StockReservation,
  StockTransfer,
  StockTransferDuplicateItem,
  StockTransferInvalidState,
  StockTransferItemNotFound,
  StockTransferLine,
  StockTransferNotFound,
  StockTransferSameWarehouse,
  StockTransferStatus,
  StockTransferWarehouseNotFound,
  StockUnavailable,
  Warehouse,
  WarehouseAlreadyExists,
} from "./src/service.ts"
export type {
  InventoryService as InventoryServiceShape,
  Item as ItemType,
  StockBalance as StockBalanceType,
  StockReservation as StockReservationType,
  StockTransfer as StockTransferType,
  StockTransferLine as StockTransferLineType,
  Warehouse as WarehouseType,
} from "./src/service.ts"
